### ISSUE TITLE
Empty html macro causes parser to fail

### ISSUE THREAD

**Issue by aDogCalledSpot** [schvv31n/yew-fmt#1]
The following code raises an error:

```rust
use yew::prelude::*;

#[function_component(App)]
pub fn app() -> Html {
    html! {}
}
```

The error:

```
error: unexpected end of input, expected curly braces
  ┌─ /path/to/tmp.rs:1:1
  │
1 │ use yew::prelude::*;
  │ ^
```

I get the same error with parentheses instead of braces and regardless of formatting.

**Comment by schvv31n** [comment]
Thank you for reporting this as well, should be fixed in v0.2.2, feel free to reopen the issue if the bug resurfaces
