### ISSUE TITLE
[Feature]: Allow Formatting Components using the Spread Operator `..`

### ISSUE THREAD

**Issue by wiseaidev** [schvv31n/yew-fmt#10]
When attempting to format [this page](https://github.com/wiseaidev/wiseai.dev/blob/main/src/pages/landing.rs), it complained about the spread operator:

```sh
error: expected an expression
   ┌─ /home/mahmoud/portfolio/wiseai.dev/src/pages/landing.rs:21:30
   │
21 │       <Hero ..profile_props />
   │                              ^
```

So, I would like to suggest enabling the formatting of components using the spread operator. Thanks!

Edit: In some cases, it works as expected, like in [this line](https://github.com/wiseaidev/wiseai.dev/blob/0b8b259084e31c2de493a8501c835aad82d9168e/src/components/projects.rs#L19) of code, probably because it is wrapped with `{}`.

**Comment by schvv31n** [comment]
Thank you for reporting this, should be fixed in v0.3.0, feel free to reopen this issue if the problem resurfaces
