### ISSUE TITLE
[Bug?] `async move` blocks are only allowed in Rust 2018 or later

### ISSUE THREAD

**Issue by wiseaidev** [schvv31n/yew-fmt#11]
Hello. Just wanted to report a bug I found while formatting [this component](https://github.com/next-rs/next-rs/blob/main/src/image.rs) at [this line](https://github.com/next-rs/next-rs/blob/e12386685b834f1de40a3c10a5cb7e262cff368b/src/image.rs#L141). The following is the error message:

```sh
error: `async move` blocks are only allowed in Rust 2018 or later
   --> /home/mahmoud/next-rs/src/image.rs:141:25
    |
141 |             spawn_local(async move {
    |                         ^^^^^^^^^^
```

That's pretty much it. Have a nice day/evening.

**Comment by schvv31n** [comment]
If you got this from calling `yew-fmt` directly, then it's not a bug: `yew-fmt` inherits all behaviour from `rustfmt`, and the latter has [this to say about Rust editions](https://github.com/rust-lang/rustfmt#rusts-editions)

**Comment by aDogCalledSpot** [comment]
You shouldn't see this if you use `RUSTFMT=yew-fmt cargo fmt`

**Comment by wiseaidev** [comment]
Thanks, @schvv31n! That helps!
