### ISSUE TITLE
Allow parentheses for short expressions

### ISSUE THREAD

**Issue by aDogCalledSpot** [schvv31n/yew-fmt#7]
The braces look good if there's a lot of content but personally I like using the round parentheses if there isn't a lot of content.

e.g.

```rust
match State {
    State::Loading => html!(<Spinner />),
    State::Ready(props) => html!(<MyComponent ..props />),
}
```

compared to

```rust
match State {
    State::Loading => html! { <Spinner /> },
    State::Ready(props) => html! { <MyComponent ..props /> },
}
```

The question is what constitutes a "short" expression. I would suggest either fits in one line or is a self-closing tag. I prefer the previous to allow something like `html!(<p>Hello World</p>)`.

**Comment by schvv31n** [comment]
Thank you for reporting this, in v0.3.0 `yew-fmt` doesn't coerce parentheses into curly brackets
