### ISSUE TITLE
Split if else blocks across multiple lines

### ISSUE THREAD

**Issue by aDogCalledSpot** [schvv31n/yew-fmt#8]
`cargo fmt` reformats the following:

```rust
if x { "true" } else { "false" }
```

to

```rust
if x { 
    "true"
} else {
    "false"
}
```

However yew-fmt reformats the following:

```rust
html! {
    if true {
        { "true" }
    } else {
        { "false" }
    }
}
```

to

```rust
html! { if true { { "true" } } else { { "false" } } }
```

I think it would be better to remain consistent with `cargo fmt` here.

------

BTW: Thanks for the hard work. Looking forward to using this :heart:

**Comment by schvv31n** [comment]
Thank you for reporting this, in the newly-released v0.3.0 `if`s are always broken up into multiple lines to mimic `rustfmt`'s formatting of `if` statements
